In [73]:
#NAME : MEHRAJ HARISH GAUD
#STUDENT ID : GAU20508518
#SUBJECT : DATA SCIENCE

In [74]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import CategoricalNB
from tabulate import tabulate

In [75]:
print("Number of rows in each column :")
for column in dataset.columns:
    print(f"{column}: {dataset[column].count()}")

Number of rows in each column :
Fever: 316800
Tiredness: 316800
Dry-Cough: 316800
Difficulty-in-Breathing: 316800
Sore-Throat: 316800
None_Sympton: 316800
Pains: 316800
Nasal-Congestion: 316800
Runny-Nose: 316800
Diarrhea: 316800
None_Experiencing: 316800
Age_0_9: 316800
Age_10_19: 316800
Age_20_24: 316800
Age_25_59: 316800
Age_60_Above: 316800
Gender_Female: 316800
Gender_Male: 316800
Gender_Transgender: 316800
Contact_Dont-Know: 316800
Contact_No: 316800
Contact_Yes: 316800
Severity_Severe: 316800


In [76]:
                    """CALCULATING PERCENTAGE OF ALL THE AGE GROUP PRONE TO SEVER COVID 19"""

total_count = 316800 

#1. AGE GROUPS
headings_age = ["AGE GROUP", " YES (IN %) ", " NO (IN %) "]
age_groups = [headings_age]

#1.1 AGE 0-9
yes_count = len(dataset[(dataset['Age_0_9'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
age_0_9 = ["AGE 0-9",percentage_of_yes,percentage_of_no]
age_groups.append(age_0_9)

#1.2 AGE 10-19
yes_count = len(dataset[(dataset['Age_10_19'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
age_10_19 = ["AGE 10-19",percentage_of_yes, percentage_of_no]
age_groups.append(age_10_19)

#1.3 AGE 20-24
yes_count = len(dataset[(dataset['Age_20_24'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
age_20_24 = ["AGE 20-24",percentage_of_yes, percentage_of_no]
age_groups.append(age_20_24)

#1.4 AGE 25-59
yes_count = len(dataset[(dataset['Age_25_59'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
age_25_59 = ["AGE 25-59",percentage_of_yes, percentage_of_no]
age_groups.append(age_25_59)

#1.5 AGE 60+
yes_count = len(dataset[(dataset['Age_60_Above'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
age_60_Above = ["AGE 60+",percentage_of_yes, percentage_of_no]
age_groups.append(age_60_Above)

print(tabulate(age_groups, headers = 'firstrow', tablefmt = 'grid'))


+-------------+----------------+---------------+
| AGE GROUP   |    YES (IN %)  |    NO (IN %)  |
+=============+================+===============+
| AGE 0-9     |              5 |            95 |
+-------------+----------------+---------------+
| AGE 10-19   |              5 |            95 |
+-------------+----------------+---------------+
| AGE 20-24   |              5 |            95 |
+-------------+----------------+---------------+
| AGE 25-59   |              5 |            95 |
+-------------+----------------+---------------+
| AGE 60+     |              5 |            95 |
+-------------+----------------+---------------+


In [72]:
                        """CALCULATING PERCENTAGE OF ALL THE GENDER PRONE TO SEVER COVID 19"""
    
#2. GENDER
headings_gender = ["GENDER", " YES (IN %) ", " NO (IN %) "]
gender_groups = [headings_gender]

#2.1 FEMALE
yes_count = len(dataset[(dataset['Gender_Female'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
female = ["FEMALE",percentage_of_yes, percentage_of_no]
gender_groups.append(female)

#2.2 MALE
yes_count = len(dataset[(dataset['Gender_Male'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
male = ["MALE",percentage_of_yes, percentage_of_no]
gender_groups.append(male)

#2.3 TRANSGENDER
yes_count = len(dataset[(dataset['Gender_Transgender'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
transgender = ["TRANSGENDER",percentage_of_yes, percentage_of_no]
gender_groups.append(transgender)

print(tabulate(gender_groups, headers = 'firstrow', tablefmt = 'grid'))

+-------------+----------------+---------------+
| GENDER      |    YES (IN %)  |    NO (IN %)  |
+=============+================+===============+
| FEMALE      |        8.33333 |       91.6667 |
+-------------+----------------+---------------+
| MALE        |        8.33333 |       91.6667 |
+-------------+----------------+---------------+
| TRANSGENDER |        8.33333 |       91.6667 |
+-------------+----------------+---------------+


In [75]:
                                """CALCULATING PERCENTAGE OF ALL THE SYMPTOM LEADING TO SEVER COVID 19"""
    
#3. SYMPTOMS

headings_symptoms = ["SYMPTOMS", " YES (IN %) ", " NO (IN %) "]
symptoms_groups = [headings_symptoms]

#3.1 FEVER
yes_count = len(dataset[(dataset['Fever'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
fever_list = ["FEVER",percentage_of_yes, percentage_of_no]
symptoms_groups.append(fever_list)

#3.2 TIREDNESS
yes_count = len(dataset[(dataset['Tiredness'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
tiredness_list = ["TIREDNESS",percentage_of_yes, percentage_of_no]
symptoms_groups.append(tiredness_list)

#3.3 DRY COUGH
yes_count = len(dataset[(dataset['Dry-Cough'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
drycough_list = ["DRY COUGH",percentage_of_yes, percentage_of_no]
symptoms_groups.append(drycough_list)

#3.4 SORE THROAT
yes_count = len(dataset[(dataset['Sore-Throat'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
sorethroat_list = ["SORE THROAT",percentage_of_yes, percentage_of_no]
symptoms_groups.append(sorethroat_list)

#3.5 DIFFICULTY IN BREATHING
yes_count = len(dataset[(dataset['Difficulty-in-Breathing'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
DIB_list = ["DIFFICULTY IN BREATHING",percentage_of_yes, percentage_of_no]
symptoms_groups.append(DIB_list)

#3.6 NONE SYMPTOMS
#yes_count = dataset[dataset['None_Sympton'] == 'Yes']['None_Sympton'].count()
yes_count = len(dataset[(dataset['None_Sympton'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
NS_list = ["NONE SYMPTOM",percentage_of_yes, percentage_of_no]
symptoms_groups.append(NS_list)


print(tabulate(symptoms_groups, headers = 'firstrow', tablefmt = 'grid'))

+-------------------------+----------------+---------------+
| SYMPTOMS                |    YES (IN %)  |    NO (IN %)  |
+=========================+================+===============+
| FEVER                   |         7.8125 |       92.1875 |
+-------------------------+----------------+---------------+
| TIREDNESS               |        12.5    |       87.5    |
+-------------------------+----------------+---------------+
| DRY COUGH               |        14.0625 |       85.9375 |
+-------------------------+----------------+---------------+
| SORE THROAT             |         7.8125 |       92.1875 |
+-------------------------+----------------+---------------+
| DIFFICULTY IN BREATHING |        12.5    |       87.5    |
+-------------------------+----------------+---------------+
| NONE SYMPTOM            |         1.5625 |       98.4375 |
+-------------------------+----------------+---------------+


In [76]:
                            """CALCULATING PERCENTAGE OF ALL THE SIGNS CONTRIBUTING TO SEVER COVID 19"""
#4. SIGNS

headings_sign = ["SIGNS", " YES (IN %) ", " NO (IN %) "]
sign_groups = [headings_sign]

#4.1 PAINS
yes_count = len(dataset[(dataset['Pains'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
pains_list = ["PAINS",percentage_of_yes, percentage_of_no]
sign_groups.append(pains_list)

#4.2 NASEL CONGESTION
yes_count = len(dataset[(dataset['Nasal-Congestion'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
nasel_congestion_list = ["NASEL CONGESTION",percentage_of_yes, percentage_of_no]
sign_groups.append(nasel_congestion_list)

#4.3 RUNNY NOSE
yes_count = len(dataset[(dataset['Runny-Nose'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
runny_nose_list = ["RUNNY NOSE",percentage_of_yes, percentage_of_no]
sign_groups.append(runny_nose_list)

#4.4 DIARRHEA
yes_count = len(dataset[(dataset['Diarrhea'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
diarrhea_list = ["DIARRHEA",percentage_of_yes, percentage_of_no]
sign_groups.append(diarrhea_list)

#4.5 NONE EXPERIENCING
yes_count = len(dataset[(dataset['None_Experiencing'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
none_experiencing_list = ["NONE EXPERIENCING",percentage_of_yes, percentage_of_no]
sign_groups.append(none_experiencing_list)

print(tabulate(sign_groups, headers = 'firstrow', tablefmt = 'grid'))

+-------------------+----------------+---------------+
| SIGNS             |    YES (IN %)  |    NO (IN %)  |
+===================+================+===============+
| PAINS             |        9.09091 |       90.9091 |
+-------------------+----------------+---------------+
| NASEL CONGESTION  |       13.6364  |       86.3636 |
+-------------------+----------------+---------------+
| RUNNY NOSE        |       13.6364  |       86.3636 |
+-------------------+----------------+---------------+
| DIARRHEA          |        9.09091 |       90.9091 |
+-------------------+----------------+---------------+
| NONE EXPERIENCING |        2.27273 |       97.7273 |
+-------------------+----------------+---------------+


In [78]:
                    """CALCULATING PERCENTAGE OF TYPES OF CONTACTS LEADING TO SEVER COVID 19"""

#5. CONTACT

headings_contact = ["CONTACT", " YES (IN %) ", " NO (IN %) "]
contact_groups = [headings_contact]

#5.1 CONTACT DON'T KNOW
yes_count = len(dataset[(dataset['Contact_Dont-Know'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
contact_dont_know_list = ["CONTACT DON'T KNOW",percentage_of_yes, percentage_of_no]
contact_groups.append(contact_dont_know_list)

#5.2 CONTACT NO
yes_count = len(dataset[(dataset['Contact_No'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
contact_no_list = ["CONTACT NO",percentage_of_yes, percentage_of_no]
contact_groups.append(contact_no_list)

#5.3 CONTACT YES
yes_count = len(dataset[(dataset['Contact_Yes'] == 'Yes') & (dataset['Severity_Severe'] == 'Yes')])
percentage_of_yes = (yes_count / total_count) * 100
percentage_of_no = 100 - percentage_of_yes
contact_yes_list = ["CONTACT YES",percentage_of_yes, percentage_of_no]
contact_groups.append(contact_yes_list)

print(tabulate(contact_groups, headers = 'firstrow', tablefmt = 'grid'))

+--------------------+----------------+---------------+
| CONTACT            |    YES (IN %)  |    NO (IN %)  |
+====================+================+===============+
| CONTACT DON'T KNOW |        8.33333 |       91.6667 |
+--------------------+----------------+---------------+
| CONTACT NO         |        8.33333 |       91.6667 |
+--------------------+----------------+---------------+
| CONTACT YES        |        8.33333 |       91.6667 |
+--------------------+----------------+---------------+


In [5]:
                                        """RETRIVING DATA FROM THE DATASET"""
    
dataset = pd.read_csv('COVID_Symptom_Checker.csv')
print(dataset.info())
#null_values = dataset.isnull().sum()
#print(null_values)
signs_and_symptoms = dataset.iloc[:, :22].values
symptoms = dataset.iloc[:, 0:6].values
signs = dataset.iloc[:, 6:10].values
age_gender = dataset.iloc[:, 11:19].values
contact = dataset.iloc[:, 19:22].values
severity = dataset.iloc[:, 22:].values
#print(signs_and_symptoms)
print(symptoms)
#print(age_gender)
#print(contact)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 23 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   Fever                    316800 non-null  object
 1   Tiredness                316800 non-null  object
 2   Dry-Cough                316800 non-null  object
 3   Difficulty-in-Breathing  316800 non-null  object
 4   Sore-Throat              316800 non-null  object
 5   None_Sympton             316800 non-null  object
 6   Pains                    316800 non-null  object
 7   Nasal-Congestion         316800 non-null  object
 8   Runny-Nose               316800 non-null  object
 9   Diarrhea                 316800 non-null  object
 10  None_Experiencing        316800 non-null  object
 11  Age_0_9                  316800 non-null  object
 12  Age_10_19                316800 non-null  object
 13  Age_20_24                316800 non-null  object
 14  Age_25_59           

In [7]:
                                            """SEVERITY LABEL"""
le = LabelEncoder()
severity_label = le.fit_transform(severity)
print("""SEVERITY VALUES:""")
print(severity)
print("SEVERITY LABELS:")
print(severity_label)
print("*******************")

SEVERITY VALUES:
[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]
SEVERITY LABELS:
[0 0 0 ... 0 0 0]
*******************


C:\Users\mehra\anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [12]:
                                    """TO CHECK PREDICTION FOR SYMPTOMS:"""

#FEVER COLUMN
fever_symptom = symptoms[:, 0:1]
fever_symptom = fever_symptom.reshape(316800)
print("\n FEVER COLUMN:")
#print(fever.shape)
print(fever_symptom)
fever_symptom = le.fit_transform(fever_symptom)
print("FEVER LABELS:")
print(fever_symptom)
print("*******************")

#TIREDNESS
tiredness_symptom = symptoms[:, 1:2]
tiredness_symptom = tiredness_symptom.reshape(316800)
print("\n TIREDNESS COLUMN:")
#print(fever.shape)
print(tiredness_symptom)
tiredness_symptom = le.fit_transform(tiredness_symptom)
print("TIREDNESS LABELS:")
print(tiredness_symptom)
print("*******************")

#DRY COUGH COLUMN
dry_cough_symptom = symptoms[:, 2:3]
dry_cough_symptom = dry_cough_symptom.reshape(316800)
print("\n DRY COUGH COLUMN:")
#print(DRY_COUGH.shape)
print(dry_cough_symptom)
dry_cough_symptom = le.fit_transform(dry_cough_symptom)
print("DRY COUGH LABELS:")
print(dry_cough_symptom)
print("*******************")

#DIFFICULTY IN BREATHING 
difficulty_in_breathing_symptom = symptoms[:, 3:4]
difficulty_in_breathing_symptom = difficulty_in_breathing_symptom.reshape(316800)
print("\n DIFFICULTY IN BREATHING COLUMN:")
#print(fever.shape)
print(difficulty_in_breathing_symptom)
difficulty_in_breathing_symptom = le.fit_transform(difficulty_in_breathing_symptom)
print("DIFFICULTY IN BREATHING LABELS:")
print(difficulty_in_breathing_symptom)
print("*******************")

#SORE THROAT
sore_throat_symptom = symptoms[:, 4:5]
sore_throat_symptom = sore_throat_symptom.reshape(316800)
print("\n SORE THROAT COLUMN:")
#print(fever.shape)
print(sore_throat_symptom)
sore_throat_symptom = le.fit_transform(sore_throat_symptom)
print("SORE THROAT LABELS:")
print(sore_throat_symptom)
print("*******************")

#NONE SYMPTOM
none_symptoms = symptoms[:, 5:6]
none_symptoms = none_symptoms.reshape(316800)
print("\n NONE SYMPTOM COLUMN:")
#print(fever.shape)
print(none_symptoms)
none_symptoms = le.fit_transform(none_symptoms)
print("NONE SYMPTOM LABELS:")
print(none_symptoms)
print("*******************")

#PREDICTION ARRAY FOR SYMPOTMS COLUMN IN THE DATASET
predictive_symptoms_array = np.array([fever_symptom, tiredness_symptom, dry_cough_symptom, difficulty_in_breathing_symptom, sore_throat_symptom,none_symptoms])
predictive_symptoms_array = predictive_symptoms_array.reshape(316800, 6)
print(predictive_symptoms_array.shape)
print(predictive_symptoms_array)


 FEVER COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
FEVER LABELS:
[1 1 1 ... 0 0 0]
*******************

 TIREDNESS COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
TIREDNESS LABELS:
[1 1 1 ... 0 0 0]
*******************

 DRY COUGH COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
DRY COUGH LABELS:
[1 1 1 ... 0 0 0]
*******************

 DIFFICULTY IN BREATHING COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
DIFFICULTY IN BREATHING LABELS:
[1 1 1 ... 0 0 0]
*******************

 SORE THROAT COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
SORE THROAT LABELS:
[1 1 1 ... 0 0 0]
*******************

 NONE SYMPTOM COLUMN:
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
NONE SYMPTOM LABELS:
[0 0 0 ... 1 1 1]
*******************
(316800, 6)
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 ...
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [13]:
                                         """PREDICTION TRAIN-TEST FOR SYMPTOMS"""

symptom_train, symptom_test, sy_train, sy_test = train_test_split(predictive_symptoms_array, severity_label, test_size = 0.7, random_state = 43)

print(symptom_train)
print("*****************")
print(symptom_test)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 ...
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
*****************
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [80]:
                                            """PREDICTION FOR SYMPTOMS"""
    
symptom_clf = CategoricalNB()
symptom_clf.fit(symptom_train, sy_train)

symptom_prediction = symptom_clf.predict(symptom_test)
print(symptom_prediction)
    

[0 0 0 ... 0 0 0]


In [81]:
                                         """ACCURACY FOR SYMPTOMS"""
    
symptom_accuracy = accuracy_score(sy_test, symptom_prediction)
print(symptom_accuracy)

0.7491522366522366


In [82]:
                                    """ERROR RATE FOR SYMPTOMS"""
    
symptom_error_rate = 1 - symptom_accuracy
print(symptom_error_rate)

0.2508477633477634


In [90]:
                                        """RAW TEST FOR SYMPTOMS"""
headings_pred_symp  = ["FEVER","TIREDNESS","DRY COUGH", "DIFFICULTY IN BREATHING","SORE THROAT", "NONE SYMPTOMS", "SEVERITY"]
pred_table = []
pred_symp = ["Yes","Yes","Yes","Yes","Yes","No"]
symp=np.array(pred_symp)
symp_converted=le.fit_transform(symp)
#print(symp_converted)
symp_converted=symp_converted.reshape(1,6)
#print(symp_converted.shape)
symptom_prediction = symptom_clf.predict(symp_converted)
if symptom_prediction == 1:
    pred_symp.append("SEVERE COVID")
else:
    pred_symp.append("NO SEVERITY")

pred_table.append(headings_pred_symp)
pred_table.append(pred_symp)

print(tabulate(pred_table, headers = 'firstrow', tablefmt = 'grid'))
    

+---------+-------------+-------------+---------------------------+---------------+-----------------+-------------+
| FEVER   | TIREDNESS   | DRY COUGH   | DIFFICULTY IN BREATHING   | SORE THROAT   | NONE SYMPTOMS   | SEVERITY    |
+=========+=============+=============+===========================+===============+=================+=============+
| Yes     | Yes         | Yes         | Yes                       | Yes           | No              | NO SEVERITY |
+---------+-------------+-------------+---------------------------+---------------+-----------------+-------------+


In [20]:
                                     """TO CHECK PREDICTION FOR SIGNS:"""

#PAINS
pains_signs = signs[:, 0:1]
pains_signs = pains_signs.reshape(316800)
print("\n PAINS COLUMN:")
#print(fever.shape)
print(pains_signs)
pains_signs = le.fit_transform(pains_signs)
print("FEVPAINSER LABELS:")
print(pains_signs)
print("*******************")

#NASEL CONGESTION
nasel_congestion_signs = signs[:, 1:2]
nasel_congestion_signs = nasel_congestion_signs.reshape(316800)
print("\n NASEL CONGESTION COLUMN:")
#print(fever.shape)
print(nasel_congestion_signs)
nasel_congestion_signs = le.fit_transform(nasel_congestion_signs)
print("NASEL CONGESTION LABELS:")
print(nasel_congestion_signs)
print("*******************")

#RUNNY NOSE
runny_nose_signs = signs[:, 2:3]
runny_nose_signs = runny_nose_signs.reshape(316800)
print("\n RUNNY NOSE COLUMN:")
#print(fever.shape)
print(runny_nose_signs)
runny_nose_signs = le.fit_transform(runny_nose_signs)
print("RUNNY NOSE LABELS:")
print(runny_nose_signs)
print("*******************")

#DIARRHEA
diarrhea_signs = signs[:, 3:4]
diarrhea_signs = diarrhea_signs.reshape(316800)
print("\n DIARRHEA COLUMN:")
#print(fever.shape)
print(diarrhea_signs)
diarrhea_signs = le.fit_transform(diarrhea_signs)
print("DIARRHEA LABELS:")
print(diarrhea_signs)
print("*******************")


predictive_sign_array = np.array([pains_signs, nasel_congestion_signs, runny_nose_signs, diarrhea_signs])
predictive_sign_array = predictive_sign_array.reshape(316800, 4)
print(predictive_sign_array.shape)
print(predictive_sign_array)



 PAINS COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
FEVPAINSER LABELS:
[1 1 1 ... 0 0 0]
*******************

 NASEL CONGESTION COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
NASEL CONGESTION LABELS:
[1 1 1 ... 0 0 0]
*******************

 RUNNY NOSE COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
RUNNY NOSE LABELS:
[1 1 1 ... 0 0 0]
*******************

 DIARRHEA COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
DIARRHEA LABELS:
[1 1 1 ... 0 0 0]
*******************
(316800, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
                                        """PREDICTION TRAIN-TEST FOR SIGNS"""
    
sign_train , sign_test, si_train, si_test = train_test_split(predictive_sign_array, severity_label, test_size = 0.5, random_state = 0)

print(sign_train)
print("*****************")
print(sign_test)

[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 ...
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]
*****************
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 ...
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]


In [22]:
                                        """PREDICTION FOR SIGNS"""
    
sign_clf = CategoricalNB()
sign_clf.fit(sign_train, si_train)

sign_prediction = sign_clf.predict(sign_test)
print(sign_prediction)
#for x in range(0, len(symptom_prediction)-1):
    #print(sign_prediction[x])

[0 0 0 ... 0 0 0]


In [23]:
                                          """ACCURACY FOR SIGNS"""
    
sign_accuracy = accuracy_score(si_test, sign_prediction)
print(sign_accuracy)

0.7491982323232323


In [61]:
                                        """ERROR RATE FOR SIGNS"""
sign_error_rate = 1 - sign_accuracy
print(sign_error_rate)

0.25080176767676765


In [93]:
                                        """RAW TEST FOR SIGNS"""

headings_pred_sign  = ["PAINS","NASAL CONGESTION","RUNNY NOSE", "DIARRHEA", "SEVERITY"]
pred_table = []
pred_sign = ["Yes","Yes","No","Yes"]
sig = np.array(pred_sign)
sig_converted  =le.fit_transform(sig)
#print(sig_converted)
sig_converted = sig_converted.reshape(1,4)
#print(sig_converted.shape)
sign_prediction = sign_clf.predict(sig_converted)
if sign_prediction == 1:
    pred_sign.append("SEVERE COVID")
else:
    pred_sign.append("NO SEVERITY")

pred_table.append(headings_pred_sign)
pred_table.append(pred_sign)

print(tabulate(pred_table, headers = 'firstrow', tablefmt = 'grid'))

+---------+--------------------+--------------+------------+-------------+
| PAINS   | NASAL CONGESTION   | RUNNY NOSE   | DIARRHEA   | SEVERITY    |
+=========+====================+==============+============+=============+
| Yes     | Yes                | No           | Yes        | NO SEVERITY |
+---------+--------------------+--------------+------------+-------------+


In [26]:
                                """TO CHECK PREDICTION FOR DIFFERENT AGE GROUP AND GENDER"""
    
#AGE 0-9
age_gender_0_9 = age_gender[:, 0:1]
age_gender_0_9 = age_gender_0_9.reshape(316800)
print("\n AGE 0-9 COLUMN:")
#print(fever.shape)
print(age_gender_0_9)
age_gender_0_9 = le.fit_transform(age_gender_0_9)
print("AGE 0-9 LABELS:")
print(age_gender_0_9)
print("*******************")

#AGE 10-19
age_gender_10_19 = age_gender[:, 1:2] 
age_gender_10_19 = age_gender_10_19.reshape(316800)
print("\n AGE 10-19 COLUMN:")
#print(fever.shape)
print(age_gender_10_19)
age_gender_10_19 = le.fit_transform(age_gender_10_19)
print("AGE 10-19 LABELS:")
print(age_gender_10_19)
print("*******************")

#AGE 20-24
age_gender_20_24 = age_gender[:, 2:3]
age_gender_20_24 = age_gender_20_24.reshape(316800)
print("\n AGE 20-24 COLUMN:")
#print(fever.shape)
print(age_gender_20_24)
age_gender_20_24 = le.fit_transform(age_gender_20_24)
print("AGE 20-24 LABELS:")
print(age_gender_20_24)
print("*******************")

#AGE 25-54
age_gender_25_54 = age_gender[:, 3:4]
age_gender_25_54 = age_gender_25_54.reshape(316800)
print("\n AGE 25-54 COLUMN:")
#print(fever.shape)
print(age_gender_25_54)
age_gender_25_54 = le.fit_transform(age_gender_25_54)
print("AGE 25-54 LABELS:")
print(age_gender_25_54)
print("*******************")

#AGE 60+
age_gender_60_above = age_gender[:, 4:5]
age_gender_60_above = age_gender_60_above.reshape(316800)
print("\n AGE 60+ COLUMN:")
#print(fever.shape)
print(age_gender_60_above)
age_gender_60_above = le.fit_transform(age_gender_60_above)
print("AGE 60+ LABELS:")
print(age_gender_60_above)
print("*******************")

#GENDER FEMALE
age_gender_female = age_gender[:, 5:6]
age_gender_female = age_gender_female.reshape(316800)    
print("\n GENDER FEMALE COLUMN:")
#print(fever.shape)
print(age_gender_female)
age_gender_female = le.fit_transform(age_gender_female)
print("AGE 60+ LABELS:")
print(age_gender_female)
print("*******************")

#GENDER MALE
age_gender_male = age_gender[:, 6:7]
age_gender_male = age_gender_male.reshape(316800)
print("\n GENDER MALE COLUMN:")
#print(fever.shape)
print(age_gender_male)
age_gender_male = le.fit_transform(age_gender_male)
print("GENDER MALE LABELS:")
print(age_gender_male)
print("*******************")

#GENDER TRANSGENDER
age_gender_transgender = age_gender[:, 7:8]
age_gender_transgender = age_gender_transgender.reshape(316800)
print("\n GENDER TRANSGENDER COLUMN:")
#print(fever.shape)
print(age_gender_transgender)
age_gender_transgender = le.fit_transform(age_gender_transgender)
print("GENDER TRANSGENDER LABELS:")
print(age_gender_transgender)
print("*******************")



predictive_age_gender_array = np.array([age_gender_0_9, age_gender_10_19, age_gender_20_24, age_gender_25_54, age_gender_60_above, age_gender_female, age_gender_male, age_gender_transgender])
predictive_age_gender_array = predictive_age_gender_array.reshape(316800, 8)
print(predictive_age_gender_array.shape)
print(predictive_age_gender_array)



 AGE 0-9 COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
AGE 0-9 LABELS:
[1 1 1 ... 0 0 0]
*******************

 AGE 10-19 COLUMN:
['No' 'No' 'No' ... 'No' 'No' 'No']
AGE 10-19 LABELS:
[0 0 0 ... 0 0 0]
*******************

 AGE 20-24 COLUMN:
['No' 'No' 'No' ... 'No' 'No' 'No']
AGE 20-24 LABELS:
[0 0 0 ... 0 0 0]
*******************

 AGE 25-54 COLUMN:
['No' 'No' 'No' ... 'No' 'No' 'No']
AGE 25-54 LABELS:
[0 0 0 ... 0 0 0]
*******************

 AGE 60+ COLUMN:
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
AGE 60+ LABELS:
[0 0 0 ... 1 1 1]
*******************

 GENDER FEMALE COLUMN:
['No' 'No' 'No' ... 'No' 'No' 'No']
AGE 60+ LABELS:
[0 0 0 ... 0 0 0]
*******************

 GENDER MALE COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
GENDER MALE LABELS:
[1 1 1 ... 0 0 0]
*******************

 GENDER TRANSGENDER COLUMN:
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
GENDER TRANSGENDER LABELS:
[0 0 0 ... 1 1 1]
*******************
(316800, 8)
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [

In [27]:
                                        """PREDICTION TRAIN-TEST FOR AGE AND GENDER"""
    
age_gender_train , age_gender_test, ag_train, ag_test = train_test_split(predictive_age_gender_array, severity_label, test_size = 0.5, random_state = 0)

print(age_gender_train)
print("*****************")
print(age_gender_test)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
*****************
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]]


In [28]:
                                        """PREDICTION FOR AGE AND GENDER"""
    
age_gender_clf = CategoricalNB()
age_gender_clf.fit(age_gender_train,ag_train)

age_gender_prediction = age_gender_clf.predict(age_gender_test)
print(age_gender_prediction)

[0 0 0 ... 0 0 0]


In [63]:
                                          """ACCURACY FOR AGE AND GENDER"""

age_gender_accuracy = accuracy_score(ag_test, age_gender_prediction)
print(age_gender_accuracy)

0.7491982323232323


In [64]:
                                        """ERROR RATE FOR AGE AND GENDER"""
age_gender_error_rate = 1 - age_gender_accuracy
print(age_gender_error_rate)

0.25080176767676765


In [95]:
                                        """RAW TEST FOR AGE AND GENDER"""

headings_pred_age  = ["AGE 0-9","AGE 10-19","AGE 20-24", "AGE 25-54","AGE 60+", "FEMALE", "MALE", "TRANSGENDER", "SEVERITY"]
pred_table = []
pred_age_gender = ["No","No","No","Yes","No","No","Yes","No"]
a_g = np.array(pred_age_gender)
a_g_converted  =le.fit_transform(a_g)
#print(a_g_converted)
a_g_converted = a_g_converted.reshape(1,8)
#print(a_g_converted.shape)
age_gender_prediction = age_gender_clf.predict(a_g_converted)
if age_gender_prediction == 1:
    pred_age_gender.append("SEVERE COVID")
else:
    pred_age_gender.append("NO SEVERITY")

pred_table.append(headings_pred_age)
pred_table.append(pred_age_gender)

print(tabulate(pred_table, headers = 'firstrow', tablefmt = 'grid'))

+-----------+-------------+-------------+-------------+-----------+----------+--------+---------------+-------------+
| AGE 0-9   | AGE 10-19   | AGE 20-24   | AGE 25-54   | AGE 60+   | FEMALE   | MALE   | TRANSGENDER   | SEVERITY    |
+===========+=============+=============+=============+===========+==========+========+===============+=============+
| No        | No          | No          | Yes         | No        | No       | Yes    | No            | NO SEVERITY |
+-----------+-------------+-------------+-------------+-----------+----------+--------+---------------+-------------+


In [69]:
                                    """TO CHECK PREDICTION FOR CONTACT COLUMNS"""
#CONTACT DON'T KNOW
contact_dont_know_cont = contact[:, 0:1]
contact_dont_know_cont = contact_dont_know_cont.reshape(316800)
print("\n CONTACT DON'T KNOW COLUMN:")
print(contact_dont_know_cont)
contact_dont_know_cont = le.fit_transform(contact_dont_know_cont)
print("CONTACT DON'T KNOW LABELS:")
print(contact_dont_know_cont)
print("*******************")

#CONTACT NO
contact_no_cont = contact[:, 1:2]
contact_no_cont = contact_no_cont.reshape(316800)
print("\n CONTACT NO COLUMN:")
#print(fever.shape)
print(contact_no_cont)
contact_no_cont = le.fit_transform(contact_no_cont)
print("CONTACT NO LABELS:")
print(contact_no_cont)
print("*******************")    

#CONTACT YES
contact_yes_cont = contact[:, 2:3]
contact_yes_cont = contact_yes_cont.reshape(316800)
print("\n CONTACT YES COLUMN:")
#print(fever.shape)
print(contact_yes_cont)
contact_yes_cont = le.fit_transform(contact_yes_cont)
print("CONTACT YES LABELS:")
print(contact_yes_cont)
print("*******************")

predictive_contact_array = np.array([contact_dont_know_cont, contact_no_cont, contact_yes_cont])
predictive_contact_array = predictive_contact_array.reshape(316800, 3)
print(predictive_contact_array.shape)
print(predictive_contact_array)


 CONTACT DON'T KNOW COLUMN:
['No' 'No' 'Yes' ... 'No' 'No' 'Yes']
CONTACT DON'T KNOW LABELS:
[0 0 1 ... 0 0 1]
*******************

 CONTACT NO COLUMN:
['No' 'Yes' 'No' ... 'No' 'Yes' 'No']
CONTACT NO LABELS:
[0 1 0 ... 0 1 0]
*******************

 CONTACT YES COLUMN:
['Yes' 'No' 'No' ... 'Yes' 'No' 'No']
CONTACT YES LABELS:
[1 0 0 ... 1 0 0]
*******************
(316800, 3)
[[0 0 1]
 [0 0 1]
 [0 0 1]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [33]:
                                 """PREDICTION TRAIN-TEST FOR CONTACT"""
    
contact_train , contact_test, c_train, c_test = train_test_split(predictive_contact_array, severity_label, test_size = 0.5, random_state = 0)

print(contact_train)
print("*****************")
print(contact_test)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 ...
 [0 1 0]
 [0 1 0]
 [1 0 0]]
*****************
[[1 0 0]
 [0 0 1]
 [0 1 0]
 ...
 [0 0 1]
 [0 0 1]
 [1 0 0]]


In [70]:
                                    """PREDICTION FOR CONTACT"""
    
contact_clf = CategoricalNB()
contact_clf.fit(contact_train, c_train)

contact_prediction = contact_clf.predict(contact_test)
print(contact_prediction)



[0 0 0 ... 0 0 0]


In [35]:
                                    """ACCURACY FOR CONTACT"""
    
contact_accuracy = accuracy_score(c_test, contact_prediction)
print(contact_accuracy)

0.7491982323232323


In [71]:
                                        """ERROR RATE FOR CONTACT"""
contact_error_rate = 1 - contact_accuracy
print(contact_error_rate)

0.25080176767676765


In [97]:
                                    """RAW TEST FOR CONTACT"""

headings_pred_contact = ["CONTACT DON'T KNOW","CONTACT NO","CONTACT YES", "SEVERITY"]
pred_table = []
pred_contact = ["Yes","No","No"]
c = np.array(pred_contact)
c_converted  =le.fit_transform(c)
#print(c_converted)
c_converted = c_converted.reshape(1,3)
#print(c_converted.shape)
contact_prediction = contact_clf.predict(c_converted)
if contact_prediction == 1:
    pred_contact.append("SEVERE COVID")
else:
    pred_contact.append("NO SEVERITY")

pred_table.append(headings_pred_contact)
pred_table.append(pred_contact)

print(tabulate(pred_table, headers = 'firstrow', tablefmt = 'grid'))

+----------------------+--------------+---------------+-------------+
| CONTACT DON'T KNOW   | CONTACT NO   | CONTACT YES   | SEVERITY    |
+======================+==============+===============+=============+
| Yes                  | No           | No            | NO SEVERITY |
+----------------------+--------------+---------------+-------------+


In [106]:
                                    """TO CHECK PREDICTION FOR ALL THE COLUMNS"""
#FEVER COLUMN
fever = signs_and_symptoms[:, 0:1]
fever = fever.reshape(316800)
print("\n FEVER COLUMN:")
print(fever)
fever = le.fit_transform(fever)
print("FEVER LABELS:")
print(fever)
print("*******************")

#TIREDNESS
tiredness = signs_and_symptoms[:, 1:2]
tiredness = tiredness.reshape(316800)
print("\n TIREDNESS COLUMN:")
print(tiredness)
tiredness = le.fit_transform(tiredness)
print("TIREDNESS LABELS:")
print(tiredness)
print("*******************")

#DRY COUGH COLUMN
dry_cough = signs_and_symptoms[:, 2:3]
dry_cough = dry_cough.reshape(316800)
print("\n DRY COUGH COLUMN:")
print(dry_cough)
dry_cough = le.fit_transform(dry_cough)
print("DRY COUGH LABELS:")
print(dry_cough)
print("*******************")

#DIFFICULTY IN BREATHING 
difficulty_in_breathing = signs_and_symptoms[:, 3:4]
difficulty_in_breathing = difficulty_in_breathing.reshape(316800)
print("\n DIFFICULTY IN BREATHING COLUMN:")
print(difficulty_in_breathing)
difficulty_in_breathing = le.fit_transform(difficulty_in_breathing)
print("DIFFICULTY IN BREATHING LABELS:")
print(difficulty_in_breathing)
print("*******************")

#SORE THROAT
sore_throat = signs_and_symptoms[:, 4:5]
sore_throat = sore_throat.reshape(316800)
print("\n SORE THROAT COLUMN:")
print(sore_throat)
sore_throat = le.fit_transform(sore_throat)
print("SORE THROAT LABELS:")
print(sore_throat)
print("*******************")

#NONE SYMPTOM
none_symptom = signs_and_symptoms[:, 5:6]
none_symptom = none_symptom.reshape(316800)
print("\n NONE SYMPTOM COLUMN:")
print(none_symptom)
none_symptom = le.fit_transform(none_symptom)
print("NONE SYMPTOM LABELS:")
print(none_symptom)
print("*******************")

#PAINS
pains = signs_and_symptoms[:, 6:7]
pains = pains.reshape(316800)
print("\n PAINS COLUMN:")
print(pains)
pains = le.fit_transform(pains)
print("FEVPAINSER LABELS:")
print(pains)
print("*******************")

#NASEL CONGESTION
nasel_congestion = signs_and_symptoms[:, 7:8]
nasel_congestion = nasel_congestion.reshape(316800)
print("\n NASEL CONGESTION COLUMN:")
print(nasel_congestion)
nasel_congestion = le.fit_transform(nasel_congestion)
print("NASEL CONGESTION LABELS:")
print(nasel_congestion)
print("*******************")

#RUNNY NOSE
runny_nose = signs_and_symptoms[:, 8:9]
runny_nose = runny_nose.reshape(316800)
print("\n RUNNY NOSE COLUMN:")
print(runny_nose)
runny_nose = le.fit_transform(runny_nose)
print("RUNNY NOSE LABELS:")
print(runny_nose)
print("*******************")

#DIARRHEA
diarrhea = signs_and_symptoms[:, 9:10]
diarrhea = diarrhea.reshape(316800)
print("\n DIARRHEA COLUMN:")
print(diarrhea)
diarrhea = le.fit_transform(diarrhea)
print("DIARRHEA LABELS:")
print(diarrhea)
print("*******************")

#NONE EXPERIENCE
none_experince = signs_and_symptoms[:, 10:11]
none_experince = none_experince.reshape(316800)
print("\n NONE EXPERIENCE COLUMN:")
print(none_experince)
none_experince = le.fit_transform(none_experince)
print("NONE EXPERIENCE LABELS:")
print(none_experince)
print("*******************")

#AGE 0-9
age_0_9 = signs_and_symptoms[:, 11:12]
age_0_9 = age_0_9.reshape(316800)
print("\n AGE 0-9 COLUMN:")
print(age_0_9)
age_0_9 = le.fit_transform(age_0_9)
print("AGE 0-9 LABELS:")
print(age_0_9)
print("*******************")

#AGE 10-19
age_10_19 = signs_and_symptoms[:, 12:13] 
age_10_19 = age_10_19.reshape(316800)
print("\n AGE 10-19 COLUMN:")
print(age_10_19)
age_10_19 = le.fit_transform(age_10_19)
print("AGE 10-19 LABELS:")
print(age_10_19)
print("*******************")

#AGE 20-24
age_20_24 = signs_and_symptoms[:, 13:14]
age_20_24 = age_20_24.reshape(316800)
print("\n AGE 20-24 COLUMN:")
print(age_20_24)
age_20_24 = le.fit_transform(age_20_24)
print("AGE 20-24 LABELS:")
print(age_20_24)
print("*******************")

#AGE 25-54
age_25_54 = signs_and_symptoms[:, 14:15]
age_25_54 = age_25_54.reshape(316800)
print("\n AGE 25-54 COLUMN:")
print(age_25_54)
age_25_54 = le.fit_transform(age_25_54)
print("AGE 25-54 LABELS:")
print(age_25_54)
print("*******************")

#AGE 60+
age_60_above = signs_and_symptoms[:, 15:16]
age_60_above = age_60_above.reshape(316800)
print("\n AGE 60+ COLUMN:")
print(age_60_above)
age_60_above = le.fit_transform(age_60_above)
print("AGE 60+ LABELS:")
print(age_60_above)
print("*******************")

#GENDER FEMALE
gender_female = signs_and_symptoms[:, 16:17]
gender_female = gender_female.reshape(316800)    
print("\n GENDER FEMALE COLUMN:")
print(gender_female)
gender_female = le.fit_transform(gender_female)
print("AGE 60+ LABELS:")
print(gender_female)
print("*******************")

#GENDER MALE
gender_male = signs_and_symptoms[:, 17:18]
gender_male = gender_male.reshape(316800)
print("\n GENDER MALE COLUMN:")
print(gender_male)
gender_male = le.fit_transform(gender_male)
print("GENDER MALE LABELS:")
print(gender_male)
print("*******************")

#GENDER TRANSGENDER
gender_transgender = signs_and_symptoms[:, 18:19]
gender_transgender = gender_transgender.reshape(316800)
print("\n GENDER TRANSGENDER COLUMN:")
print(gender_transgender)
gender_transgender = le.fit_transform(gender_transgender)
print("GENDER TRANSGENDER LABELS:")
print(gender_transgender)
print("*******************")

#CONTACT DON'T KNOW
contact_dont_know = signs_and_symptoms[:, 19:20]
contact_dont_know = contact_dont_know.reshape(316800)
print("\n CONTACT DON'T KNOW COLUMN:")
print(contact_dont_know)
contact_dont_know = le.fit_transform(contact_dont_know)
print("CONTACT DON'T KNOW LABELS:")
print(contact_dont_know)
print("*******************")

#CONTACT NO
contact_no = signs_and_symptoms[:, 20:21]
contact_no = contact_no.reshape(316800)
print("\n CONTACT NO COLUMN:")
print(contact_no)
contact_no = le.fit_transform(contact_no)
print("CONTACT NO LABELS:")
print(contact_no)
print("*******************")    

#CONTACT YES
contact_yes = signs_and_symptoms[:, 21:22]
contact_yes = contact_yes.reshape(316800)
print("\n CONTACT YES COLUMN:")
print(contact_yes)
contact_yes = le.fit_transform(contact_yes)
print("CONTACT YES LABELS:")
print(contact_yes)
print("*******************")



#PREDICTION ARRAY FOR ALL THE COLUMN IN THE DATASET
prediction_array = np.array([fever, tiredness, dry_cough, difficulty_in_breathing, sore_throat, none_symptom, pains, nasel_congestion, runny_nose, diarrhea, none_experince, age_0_9, age_10_19, age_20_24, age_25_54, age_60_above, gender_female, gender_male, gender_transgender, contact_dont_know, contact_no, contact_yes])
prediction_array = prediction_array.reshape(316800, 22)
print(prediction_array.shape)
print(prediction_array)





 FEVER COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
FEVER LABELS:
[1 1 1 ... 0 0 0]
*******************

 TIREDNESS COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
TIREDNESS LABELS:
[1 1 1 ... 0 0 0]
*******************

 DRY COUGH COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
DRY COUGH LABELS:
[1 1 1 ... 0 0 0]
*******************

 DIFFICULTY IN BREATHING COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
DIFFICULTY IN BREATHING LABELS:
[1 1 1 ... 0 0 0]
*******************

 SORE THROAT COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
SORE THROAT LABELS:
[1 1 1 ... 0 0 0]
*******************

 NONE SYMPTOM COLUMN:
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']
NONE SYMPTOM LABELS:
[0 0 0 ... 1 1 1]
*******************

 PAINS COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
FEVPAINSER LABELS:
[1 1 1 ... 0 0 0]
*******************

 NASEL CONGESTION COLUMN:
['Yes' 'Yes' 'Yes' ... 'No' 'No' 'No']
NASEL CONGESTION LABELS:
[1 1 1 ... 0 0 0]
*******************

 RUNNY NOSE COLUMN:
['Yes' 'Yes' 'Yes'

In [105]:
                                    """PREDICTION TRAIN-TEST FOR ALL COLUMN"""
    
prediction_train, prediction_test, p_train, p_test = train_test_split(prediction_array, severity_label, test_size = 0.45, random_state = 0)
print(prediction_train)
print("*****************")
print(prediction_test)


[[0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 0 0]
 [0 1 0 ... 1 0 0]]
*****************
[[1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 1]]


In [103]:
                                            """PREDICTION FOR ALL COLUMN"""
clf = CategoricalNB()
clf.fit(prediction_train, p_train)

prediction = clf.predict(prediction_test)
print(prediction)

[0 0 1 ... 0 0 0]


In [51]:
                                        """ACCURACY FOR ALL COLUMN"""
prediction_accuracy = accuracy_score(p_test, prediction)
print(prediction_accuracy)

0.6365179573512907


In [55]:
                                        """ERROR RATE FOR AGE AND GENDER"""
overall_error_rate = 1 - prediction_accuracy
print(overall_error_rate)

0.3634820426487093


In [102]:
                                        """RAW TEST FOR ALL COLUMN"""
heading_pred_all = ["SEVERITY"]
pred_table = []
pread_all = ["No","No","No","No","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","No","Yes","No","No","No","No","No","No","Yes"]
new_row=np.array(pread_all)
new_row_converted=le.fit_transform(new_row)
#print(new_row_converted)
new_row_converted=new_row_converted.reshape(1,22)
#print(new_row_converted.shape)
prediction = clf.predict(new_row_converted)
pread_all.clear()
if prediction == 1:
    pread_all.append("SEVERE COVID")
else:
    pred_contact.append("NO SEVERITY")

pred_table.append(heading_pred_all)
pred_table.append(pread_all)

print(tabulate(pred_table, headers = 'firstrow', tablefmt = 'grid'))

+--------------+
| SEVERITY     |
+==============+
| SEVERE COVID |
+--------------+
